
GET http://localhost:8080/
Accept: application/json

###

GET http://localhost:8080/1
Accept: application/json

###

POST http://localhost:8080/
Content-Type: application/json

{
  "title": "A new Todo",
  "description": "A new Todo Item",
  "completeBy": "2019-02-02"
}

###

PUT http://localhost:8080/3
Content-Type: application/json

{
  "title": "A new Todo (Updated)",
  "description": "A new Todo Item was updated",
  "completeBy": "2019-02-02",
  "completedOn": "2018-12-31"
}

###

DELETE http://localhost:8080/3
Content-Type: application/json

###

